<?php
	define('DB_HOST','localhost');
	define('DB_USER','root');
	define('DB_PASSWORD','');
	define('DB_NAME','panda_group');
	define('COOKIE_CODE','0F5ypP2cRylCalZPD6BN');
	define('DOMENA','localhost/panda_graoup/');
	define('MD5CODE','aJTk6N6EvVsJPAPDxHfO');
?>